# @see https://github.com/drevops/drupal_circleci
version: 2
aliases:
  # SSH deployment key fingerprint from CircleCI App -> Project -> Settings -> SSH Permissions.
  # Replace the value for your project.
  - &deploy_ssh_fingerprint "2d:71:4d:aa:4d:34:38:b5:8f:af:ca:3b:d4:82:6a:21"
  - &container_config
    working_directory: ~/project
    docker:
      - image: cimg/php:8.1-browsers

job-build: &job-build
  steps:
    - checkout
    - run: .circleci/build.sh
    - run: .circleci/lint.sh
    - run: .circleci/test.sh
    - run:
        command: .circleci/process-artifacts.sh
        when: always
    - store_test_results:
        path: /tmp/test_results
    - store_artifacts:
        path: /tmp/artifacts

jobs:
  build-php-8.0:
    <<: *container_config
    docker:
      - image: cimg/php:8.0-browsers
    <<: *job-build

  build-php-8.1:
    <<: *container_config
    docker:
      - image: cimg/php:8.1-browsers
    <<: *job-build

  build-php-8.0-legacy:
    <<: *container_config
    docker:
      - image: cimg/php:8.0-browsers
    environment:
      DRUPAL_VERSION: 9.2.20
      DRUPAL_PROJECT_SHA: 9.x
    <<: *job-build

  build-php-8.1-legacy:
    <<: *container_config
    docker:
      - image: cimg/php:8.1-browsers
    environment:
      DRUPAL_VERSION: 9.2.20
      DRUPAL_PROJECT_SHA: 9.x
    <<: *job-build

  deploy:
    <<: *container_config
    environment:
      DEPLOY_SSH_FINGERPRINT: *deploy_ssh_fingerprint
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - *deploy_ssh_fingerprint
      - run: DEPLOY_BRANCH=${CIRCLE_BRANCH} .circleci/deploy.sh

workflows:
  version: 2
  main:
    jobs:
      - build-php-8.0:
          filters:
            tags:
              only: /.*/
      - build-php-8.1:
          filters:
            tags:
              only: /.*/
      - build-php-8.0-legacy:
          filters:
            tags:
              only: /.*/
      - build-php-8.1-legacy:
          filters:
            tags:
              only: /.*/
      - deploy:
          requires:
            - build-php-8.0
            - build-php-8.1
            - build-php-8.0-legacy
            - build-php-8.1-legacy
          filters:
            tags:
              only: /.*/
            branches:
              # 8.x, 9.x, 8.x-1.x, 8.x-1.x, 8.x-2.x, 9.x-2.x, ci
              only: /^(?:8|9)\.x(?:\-[0-9]+\.x)?|ci$/
