# @see https://github.com/AlexSkrypnyk/drupal_extension_scaffold
version: 2

aliases:
  # SSH deployment key fingerprint from CircleCI App -> Project -> Settings -> SSH Permissions.
  # Replace with the value used for your project.
  - &deploy_ssh_fingerprint "82:3d:00:0b:fb:2f:d0:98:7c:c5:4b:73:63:b1:06:98"

  # Configuration for shared runner containers, applied to each job.
  - &container_config
    working_directory: ~/project
    docker:
      - image: cimg/php:8.2-browsers

job-build: &job-build
  steps:
    - checkout

    - run:
        name: Build the codebase
        command: .devtools/build-codebase.sh

    - run:
        name: Start built-in PHP server
        command: .devtools/start-server.sh

    - run:
        name: Provision site
        command: .devtools/provision.sh

    - run:
        name: Lint code with PHPCS
        command: vendor/bin/phpcs || [ "${CI_PHPCS_IGNORE_FAILURE:-0}" -eq 1 ]
        working_directory: build

    - run:
        name: Lint code with PHPStan
        command: vendor/bin/phpstan || [ "${CI_PHPSTAN_IGNORE_FAILURE:-0}" -eq 1 ]
        working_directory: build

    - run:
        name: Lint code with Rector
        command: vendor/bin/rector --clear-cache --dry-run || [ "${CI_RECTOR_IGNORE_FAILURE:-0}" -eq 1 ]
        working_directory: build

    - run:
        name: Lint code with PHPMD
        command: vendor/bin/phpmd . text phpmd.xml || [ "${CI_PHPMD_IGNORE_FAILURE:-0}" -eq 1 ]
        working_directory: build

    - run:
        name: Lint code with Twigcs
        command: vendor/bin/twigcs || [ "${CI_TWIGCS_IGNORE_FAILURE:-0}" -eq 1 ]
        working_directory: build

    - run:
        name: Run tests
        command: .devtools/test.sh || [ "${CI_TEST_IGNORE_FAILURE:-0}" -eq 1 ]

    - run:
        name: Process artifacts
        command: |
          if [ -d "build/web/sites/simpletest/browser_output" ]; then
            mkdir -p /tmp/artifacts/simpletest
            cp -Rf "build/web/sites/simpletest/browser_output/." /tmp/artifacts/simpletest
          fi
        when: always

    - store_test_results:
        path: /tmp/test_results

    - store_artifacts:
        path: /tmp/artifacts

jobs:
  build-php-8.1:
    <<: *container_config
    docker:
      - image: cimg/php:8.1-browsers
    <<: *job-build

  build-php-8.2:
    <<: *container_config
    docker:
      - image: cimg/php:8.2-browsers
    <<: *job-build

  build-php-8.1-legacy:
    <<: *container_config
    docker:
      - image: cimg/php:8.1-browsers
    environment:
      DRUPAL_VERSION: 9.5
      DRUPAL_PROJECT_SHA: 9.x
    <<: *job-build

  build-php-8.2-legacy:
    <<: *container_config
    docker:
      - image: cimg/php:8.2-browsers
    environment:
      DRUPAL_VERSION: 9.5
      DRUPAL_PROJECT_SHA: 9.x
    <<: *job-build

  build-php-8.2-next:
    <<: *container_config
    docker:
      - image: cimg/php:8.2-browsers
    environment:
      DRUPAL_VERSION: 10@beta
    <<: *job-build

  deploy:
    <<: *container_config
    environment:
      DEPLOY_SSH_FINGERPRINT: *deploy_ssh_fingerprint
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - *deploy_ssh_fingerprint
      - run: DEPLOY_BRANCH=${DEPLOY_BRANCH:-${CIRCLE_BRANCH}} .devtools/deploy.sh

workflows:
  version: 2
  main:
    jobs:
      - build-php-8.1:
          filters:
            tags:
              only: /.*/
      - build-php-8.2:
          filters:
            tags:
              only: /.*/
      - build-php-8.1-legacy:
          filters:
            tags:
              only: /.*/
      - build-php-8.2-legacy:
          filters:
            tags:
              only: /.*/
      - build-php-8.2-next:
          filters:
            tags:
              only: /.*/
      - deploy:
          requires:
            - build-php-8.1
            - build-php-8.2
            - build-php-8.1-legacy
            - build-php-8.2-legacy
            - build-php-8.2-next
          filters:
            tags:
              only: /.*/
            branches:
              # 1.0.x, 2.3.x, 9.x, 10.x, 9.x-2.x, ci, ci-test
              only: /^[0-9]+.[0-9]+.x$|^[0-9]+.x(?:\-[0-9]+\.x)?$|^ci.*/
